import { Header } from "@/modules/Header";
import Head from "next/head";
import { ReactNode } from "react";

export default function Home() {
	return (
		<>
			<Head>
				<title>Веб-сервис для грузоперевозок</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>in dev</main>
		</>
	);
}

Home.getLayout = (page: ReactNode) => (
	<>
	<Header/>
		{page}
	</>
);